# Generated by Django 4.0 on 2022-01-18 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_profile_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='rank',
        ),
    ]
