# Generated by Django 4.0 on 2022-01-18 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_profile_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rank',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
