# Generated by Django 3.2.9 on 2022-01-20 08:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_profile_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='rank',
            field=models.PositiveIntegerField(default=datetime.datetime(2022, 1, 20, 8, 39, 27, 297848, tzinfo=utc), verbose_name='rank'),
            preserve_default=False,
        ),
    ]
