# Generated by Django 3.2.9 on 2022-01-20 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_profile_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='rank',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
